language: node_js
node_js:
  - "8.11.4"

sudo: required

cache:
  directories:
    - "node_modules"

before_install:
  - sudo add-apt-repository ppa:ethereum/ethereum -y
  - sudo apt-get update
  - sudo apt-get install solc
  # Install Ganache
  - npm i -g ganache-cli@6.1.0
  - ganache-cli &>/dev/null &
  - sleep 6 # wait for ganache-cli
  - curl -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":0}' http://localhost:8545
  # Install IPFS
  - wget "https://dist.ipfs.io/go-ipfs/v0.4.9/go-ipfs_v0.4.9_linux-amd64.tar.gz" -O /tmp/ipfs.tar.gz
  - pushd . && cd $HOME/bin && tar -xzvf /tmp/ipfs.tar.gz && popd
  - export PATH="$HOME/bin/go-ipfs:$PATH"
  - ipfs init
  - ipfs daemon &>/dev/null &
  - sleep 5
  - curl http://localhost:5001/api/v0/id

install:
  - npm i

script:
  - npm run contracts:compile
  - npm run contracts:migrate
  - npm run lint
  - npm run test
  - npm run cc
